package com.michael.pojo;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.title
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.desrciption
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private String desrciption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.updateTime
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.view
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private Integer view;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.author
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.content
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.title
     *
     * @return the value of t_blog.title
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.title
     *
     * @param title the value for t_blog.title
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.desrciption
     *
     * @return the value of t_blog.desrciption
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public String getDesrciption() {
        return desrciption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.desrciption
     *
     * @param desrciption the value for t_blog.desrciption
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setDesrciption(String desrciption) {
        this.desrciption = desrciption == null ? null : desrciption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.updateTime
     *
     * @return the value of t_blog.updateTime
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.updateTime
     *
     * @param updatetime the value for t_blog.updateTime
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.view
     *
     * @return the value of t_blog.view
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.view
     *
     * @param view the value for t_blog.view
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.author
     *
     * @return the value of t_blog.author
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.author
     *
     * @param author the value for t_blog.author
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.content
     *
     * @return the value of t_blog.content
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.content
     *
     * @param content the value for t_blog.content
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}