package com.michael.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Friendship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friendship.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friendship.user_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friendship.friend_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private String friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friendship.id
     *
     * @return the value of t_friendship.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friendship.id
     *
     * @param id the value for t_friendship.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friendship.user_id
     *
     * @return the value of t_friendship.user_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friendship.user_id
     *
     * @param userId the value for t_friendship.user_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friendship.friend_id
     *
     * @return the value of t_friendship.friend_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friendship.friend_id
     *
     * @param friendId the value for t_friendship.friend_id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }
}