package com.michael.pojo;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.sender
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.receiver
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.status
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.sendtime
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    private Date sendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.sender
     *
     * @return the value of t_notice.sender
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.sender
     *
     * @param sender the value for t_notice.sender
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.receiver
     *
     * @return the value of t_notice.receiver
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.receiver
     *
     * @param receiver the value for t_notice.receiver
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.status
     *
     * @return the value of t_notice.status
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.status
     *
     * @param status the value for t_notice.status
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.sendtime
     *
     * @return the value of t_notice.sendtime
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.sendtime
     *
     * @param sendtime the value for t_notice.sendtime
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }
}