package com.michael.mapper;

import com.michael.pojo.Blog;
import com.michael.pojo.User;

import java.util.List;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    Blog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    List<Blog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog
     *
     * @mbggenerated Mon Jun 27 00:09:24 CST 2022
     */
    int updateByPrimaryKey(Blog record);

    List<Blog> selectByAuthor(String author);

    List<String> findGroupYear(String author);

    List<Blog> findByYear(String year,String author);

    /**
     * 设置浏览次数+1
     * @param id
     */
    void updateViewById(Long id);


    /**
     * 更新点赞数，未实现
     */
    void updateLikeById(Long id);

    /**
     * limit限制查询文章
     * @param author
     * @param limit
     * @return
     */
    List<Blog> selectWithLimit(String author,Integer limit,Integer eachPageCount);

    /**
     * 根据作者返回文章总数
     * @param author
     * @return
     */
    Integer selectCountByAuthor(String author);

    String selectAuthorById(Long id);
}