package com.michael.mapper;

import com.michael.pojo.Notice;
import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    Notice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    List<Notice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Tue Jun 28 09:10:37 CST 2022
     */
    int updateByPrimaryKey(Notice record);

    /**
     *
     * @param userId
     * @return
     */
    List<Notice> selectByUserId(Integer userId);

    Integer selectBySAndR(Integer senderId,Integer userId);
}